### ISSUE TITLE
XT Headlights

### ISSUE THREAD

**Issue by seavm11** [chrisstring/_templatesite#11]
Hey, not sure why but the XT headlight template is not showing up.  I tried to access it through:

Lights and Mounting Options > All > Headlights

**Comment by chrisstring** [comment]
So whoever decided to make this smartsheet a while back wasn't consistent through out so what that means is that we will need to migrate items from the 

Lights & Mounts category to the Lights category.  I believe I migrated over Tail Lights, but we will continue to migrate them over out of that category, it's just a little slow going
