### ISSUE TITLE
remove images from template

### ISSUE THREAD

**Issue by seavm11** [chrisstring/_templatesite#13]
Can you remove alt4 and alt5 from the a-pillar mount template?

file:///Volumes/public/Retouch%20Team/WORKING%20SCRIPTS/Script%20Sandbox/_github/_templatesite/templatesite-working.htm

**Comment by seavm11** [comment]
![screen shot 2018-04-17 at 8 29 32 am](https://user-images.githubusercontent.com/37837711/38869690-86074ff6-4219-11e8-9987-f1bafb7ae6c9.png)

**Comment by chrisstring** [comment]
Removed images in scene7, this fixes #13
